version: 2.1

jobs:
  build:
    working_directory: ~/hl7

    docker:
      - image: careport/syndicate-circleci:0.2.0

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rspec
